# Generated by Django 4.0.3 on 2022-09-06 14:54

import db_module.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.AutoField(primary_key=True, serialize=False)),
                ('chat_name', models.CharField(default='', max_length=50)),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.URLField(default='')),
                ('telegram', models.URLField(default='')),
                ('instagram', models.URLField(default='')),
                ('web_site', models.URLField(default='')),
                ('email', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(default='/test_default_place.png', upload_to='')),
                ('about', models.TextField(default='')),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('timetable', models.TextField(default='')),
                ('is_private', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('MEETING', 'MEETING'), ('MUSIC', 'MUSIC'), ('FESTIVAL', 'FESTIVAL'), ('PERFORMANCE', 'PERFORMANCE'), ('ALL', 'ALL'), ('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION')], default='OTHER', max_length=15)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('contacts', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='db_module.contacts')),
                ('invited_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=50)),
                ('is_shareable', models.BooleanField(blank=True, default=False)),
                ('events', models.ManyToManyField(to='db_module.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilterSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MEETING', 'MEETING'), ('MUSIC', 'MUSIC'), ('FESTIVAL', 'FESTIVAL'), ('PERFORMANCE', 'PERFORMANCE'), ('ALL', 'ALL'), ('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION')], default='ALL', max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('subscription', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=6, default=0.0, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('about', models.TextField(default='')),
                ('image', models.ImageField(default='/default_icon.png', upload_to=db_module.models.upload_to_by_id)),
                ('black_list', models.ManyToManyField(related_name='blacklist', to=settings.AUTH_USER_MODEL)),
                ('filter_settings', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filters', to='db_module.filtersettings')),
                ('subscriptions', models.ManyToManyField(related_name='whitelist', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_contacts', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='db_module.contacts')),
            ],
        ),
        migrations.CreateModel(
            name='ShareableEventPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='db_module.eventplan')),
                ('redactors', models.ManyToManyField(related_name='redactors', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventPositionInPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_module.event')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_module.eventplan')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(default='', max_length=30)),
                ('text', models.TextField()),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_module.chat')),
            ],
        ),
    ]
