# Generated by Django 4.0.3 on 2022-09-06 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_module', '0002_alter_event_type_alter_filtersettings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vk',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='web_site',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='invited_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'PERFORMANCE'), ('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION'), ('MUSIC', 'MUSIC'), ('ALL', 'ALL'), ('MEETING', 'MEETING')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'PERFORMANCE'), ('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION'), ('MUSIC', 'MUSIC'), ('ALL', 'ALL'), ('MEETING', 'MEETING')], default='ALL', max_length=15),
        ),
    ]
