# Generated by Django 4.0.3 on 2022-09-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0004_alter_event_date_alter_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('MUSIC', 'MUSIC'), ('ALL', 'ALL'), ('EXHIBITION', 'EXHIBITION'), ('FESTIVAL', 'FESTIVAL'), ('MEETING', 'MEETING'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('MUSIC', 'MUSIC'), ('ALL', 'ALL'), ('EXHIBITION', 'EXHIBITION'), ('FESTIVAL', 'FESTIVAL'), ('MEETING', 'MEETING'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE')], default='ALL', max_length=15),
        ),
    ]
