# Generated by Django 4.0.3 on 2022-09-08 13:23

import db_module.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_module', '0006_alter_event_type_alter_filtersettings_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False)),
                ('about', models.TextField(default='')),
                ('image', models.ImageField(default='/default_icon.png', upload_to=db_module.models.upload_to_by_id)),
                ('black_list', models.ManyToManyField(blank=True, related_name='blacklist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vk',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='web_site',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION'), ('MUSIC', 'MUSIC'), ('PERFORMANCE', 'PERFORMANCE'), ('MEETING', 'MEETING'), ('ALL', 'ALL')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='eventplan',
            name='is_shareable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION'), ('MUSIC', 'MUSIC'), ('PERFORMANCE', 'PERFORMANCE'), ('MEETING', 'MEETING'), ('ALL', 'ALL')], default='ALL', max_length=15),
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contacts',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='db_module.contacts'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='filter_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='filters', to='db_module.filtersettings'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
