# Generated by Django 4.0.3 on 2022-09-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0007_userprofile_alter_contacts_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vk',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='web_site',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('ALL', 'ALL'), ('MUSIC', 'MUSIC'), ('EXHIBITION', 'EXHIBITION'), ('MEETING', 'MEETING'), ('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('ALL', 'ALL'), ('MUSIC', 'MUSIC'), ('EXHIBITION', 'EXHIBITION'), ('MEETING', 'MEETING'), ('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE')], default='ALL', max_length=15),
        ),
    ]
