# Generated by Django 4.0.3 on 2022-09-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0008_alter_contacts_email_alter_contacts_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='instagram',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vk',
            field=models.CharField(default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('ALL', 'ALL'), ('MUSIC', 'MUSIC'), ('OTHER', 'OTHER'), ('FESTIVAL', 'FESTIVAL'), ('PERFORMANCE', 'PERFORMANCE'), ('EXHIBITION', 'EXHIBITION'), ('MEETING', 'MEETING')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('ALL', 'ALL'), ('MUSIC', 'MUSIC'), ('OTHER', 'OTHER'), ('FESTIVAL', 'FESTIVAL'), ('PERFORMANCE', 'PERFORMANCE'), ('EXHIBITION', 'EXHIBITION'), ('MEETING', 'MEETING')], default='ALL', max_length=15),
        ),
    ]
