# Generated by Django 4.0.3 on 2022-09-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0009_alter_contacts_instagram_alter_contacts_telegram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'PERFORMANCE'), ('ALL', 'ALL'), ('EXHIBITION', 'EXHIBITION'), ('OTHER', 'OTHER'), ('MEETING', 'MEETING'), ('FESTIVAL', 'FESTIVAL'), ('MUSIC', 'MUSIC')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'PERFORMANCE'), ('ALL', 'ALL'), ('EXHIBITION', 'EXHIBITION'), ('OTHER', 'OTHER'), ('MEETING', 'MEETING'), ('FESTIVAL', 'FESTIVAL'), ('MUSIC', 'MUSIC')], default='ALL', max_length=15),
        ),
    ]
