# Generated by Django 4.0.3 on 2022-09-09 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0010_alter_event_type_alter_filtersettings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vk',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='web_site',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('MUSIC', 'MUSIC'), ('MEETING', 'MEETING'), ('OTHER', 'OTHER'), ('FESTIVAL', 'FESTIVAL'), ('ALL', 'ALL'), ('PERFORMANCE', 'PERFORMANCE'), ('EXHIBITION', 'EXHIBITION')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('MUSIC', 'MUSIC'), ('MEETING', 'MEETING'), ('OTHER', 'OTHER'), ('FESTIVAL', 'FESTIVAL'), ('ALL', 'ALL'), ('PERFORMANCE', 'PERFORMANCE'), ('EXHIBITION', 'EXHIBITION')], default='ALL', max_length=15),
        ),
    ]
