# Generated by Django 4.0.3 on 2022-09-09 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0011_alter_contacts_email_alter_contacts_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='instagram',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='telegram',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='vk',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='web_site',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE'), ('MEETING', 'MEETING'), ('ALL', 'ALL'), ('MUSIC', 'MUSIC'), ('EXHIBITION', 'EXHIBITION')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE'), ('MEETING', 'MEETING'), ('ALL', 'ALL'), ('MUSIC', 'MUSIC'), ('EXHIBITION', 'EXHIBITION')], default='ALL', max_length=15),
        ),
    ]
