# Generated by Django 4.0.3 on 2022-09-09 06:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_module', '0012_alter_contacts_email_alter_contacts_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscribers_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION'), ('ALL', 'ALL'), ('PERFORMANCE', 'PERFORMANCE'), ('MEETING', 'MEETING'), ('MUSIC', 'MUSIC')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION'), ('ALL', 'ALL'), ('PERFORMANCE', 'PERFORMANCE'), ('MEETING', 'MEETING'), ('MUSIC', 'MUSIC')], default='ALL', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='subscriptions',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
