# Generated by Django 4.0.3 on 2022-09-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0014_alter_event_type_alter_filtersettings_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION'), ('ALL', 'ALL'), ('PERFORMANCE', 'PERFORMANCE'), ('MEETING', 'MEETING'), ('MUSIC', 'MUSIC'), ('FESTIVAL', 'FESTIVAL')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION'), ('ALL', 'ALL'), ('PERFORMANCE', 'PERFORMANCE'), ('MEETING', 'MEETING'), ('MUSIC', 'MUSIC'), ('FESTIVAL', 'FESTIVAL')], default='ALL', max_length=15),
        ),
    ]
