# Generated by Django 4.0.3 on 2022-09-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0016_alter_event_type_alter_filtersettings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('FESTIVAL', 'FESTIVAL'), ('MEETING', 'MEETING'), ('PERFORMANCE', 'PERFORMANCE'), ('ALL', 'ALL'), ('OTHER', 'OTHER'), ('MUSIC', 'MUSIC'), ('EXHIBITION', 'EXHIBITION')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('FESTIVAL', 'FESTIVAL'), ('MEETING', 'MEETING'), ('PERFORMANCE', 'PERFORMANCE'), ('ALL', 'ALL'), ('OTHER', 'OTHER'), ('MUSIC', 'MUSIC'), ('EXHIBITION', 'EXHIBITION')], default='ALL', max_length=15),
        ),
    ]
