# Generated by Django 4.0.3 on 2022-09-12 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_module', '0017_alter_event_type_alter_filtersettings_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('MEETING', 'MEETING'), ('MUSIC', 'MUSIC'), ('ALL', 'ALL'), ('EXHIBITION', 'EXHIBITION'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE'), ('FESTIVAL', 'FESTIVAL')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('MEETING', 'MEETING'), ('MUSIC', 'MUSIC'), ('ALL', 'ALL'), ('EXHIBITION', 'EXHIBITION'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE'), ('FESTIVAL', 'FESTIVAL')], default='ALL', max_length=15),
        ),
    ]
