# Generated by Django 4.0.3 on 2022-09-13 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0018_alter_event_author_alter_event_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('EXHIBITION', 'EXHIBITION'), ('MUSIC', 'MUSIC'), ('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE'), ('ALL', 'ALL'), ('MEETING', 'MEETING')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('EXHIBITION', 'EXHIBITION'), ('MUSIC', 'MUSIC'), ('FESTIVAL', 'FESTIVAL'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE'), ('ALL', 'ALL'), ('MEETING', 'MEETING')], default='ALL', max_length=15),
        ),
    ]
