# Generated by Django 4.0.3 on 2022-09-13 04:16

import db_module.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db_module', '0020_remove_event_invited_users_remove_event_is_private_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invited_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='contacts',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='event_contacts', to='db_module.contacts'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='/test_default_place.png', upload_to=db_module.models.upload_to_by_id),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'PERFORMANCE'), ('OTHER', 'OTHER'), ('MEETING', 'MEETING'), ('MUSIC', 'MUSIC'), ('FESTIVAL', 'FESTIVAL'), ('ALL', 'ALL'), ('EXHIBITION', 'EXHIBITION')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'PERFORMANCE'), ('OTHER', 'OTHER'), ('MEETING', 'MEETING'), ('MUSIC', 'MUSIC'), ('FESTIVAL', 'FESTIVAL'), ('ALL', 'ALL'), ('EXHIBITION', 'EXHIBITION')], default='ALL', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contacts',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userprofile_contacts', to='db_module.contacts'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='filter_settings',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='userprofile_filters', to='db_module.filtersettings'),
        ),
    ]
