# Generated by Django 4.0.3 on 2022-09-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0021_event_invited_users_event_is_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='event',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'PERFORMANCE'), ('MUSIC', 'MUSIC'), ('FESTIVAL', 'FESTIVAL'), ('ALL', 'ALL'), ('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION'), ('MEETING', 'MEETING')], default='OTHER', max_length=15),
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('PERFORMANCE', 'PERFORMANCE'), ('MUSIC', 'MUSIC'), ('FESTIVAL', 'FESTIVAL'), ('ALL', 'ALL'), ('OTHER', 'OTHER'), ('EXHIBITION', 'EXHIBITION'), ('MEETING', 'MEETING')], default='ALL', max_length=15),
        ),
    ]
