# Generated by Django 4.0.3 on 2022-09-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_module', '0022_remove_event_date_remove_event_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='invited_users',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timetable',
        ),
        migrations.RemoveField(
            model_name='event',
            name='type',
        ),
        migrations.AlterField(
            model_name='filtersettings',
            name='type',
            field=models.CharField(choices=[('MEETING', 'MEETING'), ('OTHER', 'OTHER'), ('PERFORMANCE', 'PERFORMANCE'), ('ALL', 'ALL'), ('FESTIVAL', 'FESTIVAL'), ('MUSIC', 'MUSIC'), ('EXHIBITION', 'EXHIBITION')], default='ALL', max_length=15),
        ),
    ]
